import os
import tensorflow as tf
from tensorflow.keras import layers, applications, optimizers, models

import config as cfg
import datasets as dtst
import models as mdl

# this file contains all utilities commands to train/evaluate and etc models

def classification_train(
        dataset_path="wrk/mixed/",      # use dataset from this path
        from_checkpoint_path = None,    # load checkpoint before training (if set)
        checkpoint_path = "checkpoints/default.set_model.weights.h5",         # store checkpoints periodically here (if set)
        finetune = False,               # enable fine_tune if enabled (retrain base model)
        finetune_lr = 1e-5,             # adjust learning rate for finetune (useful for finetuning, since it should be smaller than usual LR)
        epoch_number = 100              # default max
        ):
    model = mdl.SetgameClassificationModel()

    # if "from" checkpoint path is set - use it
    if not from_checkpoint_path is None:
        model.load(from_checkpoint_path)

    # training params
    optimizer = optimizers.Adam(learning_rate=1e-3)
    loss_fns = model.get_loss_fns()

    # enable fine_tune mode
    model.set_fine_tuning(finetune)
    if finetune:
        optimizer.learning_rate = finetune_lr

    # --- (Custom Training Loop) ---
    @tf.function # speed up graf (GPU/NPU optimization)
    def train_step(images, labels):
        with tf.GradientTape() as tape:
            predictions = model(images, training=True)
            # Суммируем потери от всех голов
            total_loss = sum([loss_fns[i](labels[i], predictions[i]) for i in range(4)])
        
        gradients = tape.gradient(total_loss, model.trainable_variables)
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))
        return total_loss
    
    # training - generated by gemini, doesn't have needed functionality
    train_ds, val_ds = dtst.ClassificationDataset.create(dataset_path)

    for epoch in range(epoch_number):
        print(f"\n--- Epoch {epoch + 1}/{epoch_number} ---")
        
        epoch_loss = 0
        num_batches = 0
        
        for images, labels in train_ds:
            loss = train_step(images, labels)
            epoch_loss += loss
            num_batches += 1
            
            if num_batches % 10 == 0:
                print(f"batch {num_batches}, Current Loss: {loss:.4f}")

        print(f"Avg Loss for epoch: {epoch_loss / num_batches:.4f}")

        if not checkpoint_path is None:
            model.save_weights(checkpoint_path)
            print(f"Checkpoint is stored: {checkpoint_path}")


# main utility code
import argparse
import sys

def main():
    parser = argparse.ArgumentParser(
        description="System entry point for multiple ML commands",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    
    # Create subparsers for different commands
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # --- classification_train ---
    train_parser = subparsers.add_parser(
        "classification_train", 
        help="Start the model training process"
    )    
    train_parser.add_argument("--dataset_path", type=str, default="wrk/mixed/", 
                              help="Path to dataset directory")
    train_parser.add_argument("--from_checkpoint_path", type=str, default=None, 
                              help="Initial weights to load")
    train_parser.add_argument("--checkpoint_path", type=str, default="checkpoints/default.set_model.weights.h5", 
                              help="Directory to save periodic checkpoints")    
    train_parser.add_argument("--finetune", action="store_true", 
                              help="Enable fine-tuning of the base model")
    train_parser.add_argument("--finetune_lr", type=float, default=1e-5, 
                              help="Learning rate for fine-tuning")
    train_parser.add_argument("--epoch_number", type=int, default=100, 
                              help="Total number of epochs")


    #split and print debug
    params = vars(parser.parse_args())
    command = params.pop("command")
    if not command is None:
        print(f"Got command '{command}' with params {params}")

    try:
        if command == "classification_train":
                classification_train(**params)
        elif command is None:
            parser.print_help()            
    except KeyboardInterrupt:
        print("\n[System] Process interrupted.")
        sys.exit(0)
    except Exception as e:
        print(f"\n[System Error] {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()